name: build
on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        compiler: [gcc]  # 只使用 gcc 编译器
        crypto: [openssl]  # 只使用 openssl 加密库
        bittorrent: [with-bt]  # 只设置 BitTorrent 为 with-bt
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup environment
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && sudo apt-get install -y \
          g++-12 \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev \
          libc-ares-dev \
          zlib1g-dev \
          libsqlite3-dev \
          libssh2-1-dev \
          libcppunit-dev

    - name: Setup GCC
      if: runner.os == 'Linux' && matrix.compiler == 'gcc'
      run: |
        echo "CC=gcc-12" >> $GITHUB_ENV
        echo "CXX=g++-12" >> $GITHUB_ENV

    - name: Libtool setup
      run: |
        autoreconf -i

    - name: Setup compiler flags
      run: |
        asanflags="-fsanitize=address,undefined -fno-sanitize-recover=undefined"
        CPPFLAGS="$asanflags -g3"
        LDFLAGS="$asanflags"
        echo "CPPFLAGS=$CPPFLAGS" >> $GITHUB_ENV
        echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV

    - name: Configure autotools (Linux, openssl)
      if: runner.os == 'Linux' && matrix.crypto == 'openssl'
      run: |
        ./configure --without-gnutls --with-openssl $FEATURE_FLAGS

    - name: Build Aria2
      run: |
        make -j"$(nproc || sysctl -n hw.ncpu)" check
